export const SHOW_STATUS_MODAL = 'SHOW_STATUS_MODAL';

export const HIDE_STATUS_MODAL = 'HIDE_STATUS_MODAL';

export const STATUS_MODAL_CONTENT = 'STATUS_MODAL_CONTENT';

export const STATUS_MODAL_TITLE = 'STATUS_MODAL_TITLE';